services:
  postgres:
    image: postgres:13.11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - prefect-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prefect -d prefect"]
      interval: 60s
      timeout: 60s
      retries: 5

  prefect-server:
    image: prefecthq/prefect:2.16.4-python3.10
    command: prefect server start --host 0.0.0.0 --port 4200
    ports:
      - "4200:4200"
    depends_on:
      - postgres
    networks:
      - prefect-net

  prefect-agent:
    build:
      context: ..
      dockerfile: ./infra/Dockerfile
    command: prefect agent start --pool artigo-pool --work-queue queue-pool
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
      - DB_USER=prefect
      - DB_PASSWORD=prefect
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=prefect
    volumes:
      - ../:/app
    depends_on:
      - prefect-server
    networks:
      - prefect-net

  dash-app:
    build:
      context: ..
      dockerfile: ./infra/Dockerfile.dash
    ports:
      - "8050:8050"
    environment:
      - DB_USER=prefect
      - DB_PASSWORD=prefect
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=prefect
    depends_on:
      - postgres
    networks:
      - prefect-net

volumes:
  pgdata:
  prefect_data:

networks:
  prefect-net: