version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - prefect-net

  prefect-server:
    image: prefecthq/prefect:2.16.4-python3.12
    command: prefect server start --host 0.0.0.0 --port 4200
    environment:
      - PREFECT_HOME=/root/.prefect
      - PREFECT_API_URL=http://prefect-server:4200/api
    ports:
      - "4200:4200"
    volumes:
      - prefect_data:/root/.prefect
    depends_on:
      - postgres
    networks:
      - prefect-net

  prefect-agent:
    build: .
    command: prefect agent start --pool default-agent-pool
    environment:
      - PREFECT_HOME=/root/.prefect
      - PREFECT_API_URL=http://prefect-server:4200/api
    volumes:
      - ../:/app/Trabalho_final
      - ./data:/app/data
    depends_on:
      - prefect-server
    networks:
      - prefect-net

volumes:
  pgdata:
  prefect_data:

networks:
  prefect-net:
