# Conteúdo do seu docker-compose.yml aqui
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prefect -d prefect"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - prefect-net

  prefect-server:
    image: prefecthq/prefect:2.16.4-python3.12
    command: prefect server start --host 0.0.0.0 --port 4200
    environment:
      PREFECT_HOME: /root/.prefect
      PREFECT_API_URL: http://prefect-server:4200/api
    ports:
      - "4200:4200"
    volumes:
      - prefect_data:/root/.prefect
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - prefect-net

  prefect-agent:
    build:
      context: .. # Contexto é o diretório pai, onde src e simulacao_resultados estão
      dockerfile: infra/Dockerfile # Dockerfile dentro da pasta infra
    command: prefect agent start --pool default-agent-pool
    environment:
      PREFECT_HOME: /root/.prefect
      PREFECT_API_URL: http://prefect-server:4200/api
    volumes:
      - ../src:/app/src # Monta o src do host no container
      - ../simulacao_resultados:/app/simulacao_resultados # Monta simulacao_resultados do host
    depends_on:
      prefect-server:
        condition: service_started
    networks:
      - prefect-net

volumes:
  pgdata:
  prefect_data:

networks:
  prefect-net: